model_name: v2
reader_settings:
  gpu: auto
  quantize: true
  detector: true
  recognizer: true
readtext_settings:
  decoder: beamsearch
  text_threshold: 0.7
  low_text: 0.4
  link_threshold: 0.4
  contrast_ths: 0.1
  min_size: 10
  batch_size: 1
  paragraph: false
preprocessing:
  resize: true
  resize_scale: 2
  deskew: true
  autocrop_border: false
  autocrop_margin_ratio: 0.01
  illumination_correct: true
  illumination_kernel_size: 51
  grayscale: true
  clahe: false
  clahe_clip_limit: 2
  clahe_grid_size: 8
  denoise: false
  sharpen: true
  morphology: false
  morphology_op: dilate
  morphology_kernel_size: 2
  threshold: true
  threshold_block_size: 35
  threshold_c: 11
