services:
  paddleocr:
    build: .
    volumes:
      - ./inputs:/data/inputs
      - ./outputs:/data/outputs
      - ./configurations:/data/configurations
      - paddlex_model_cache:/root/.paddlex
    command: ["model_v1"]

volumes:
  paddlex_model_cache: